name: Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'
    - name: Install dependencies
      run: npm install
    - name: Test & build
      run: npm run build:prod

    - name: Deploy with Vercel
      id: deploy
      uses: amondnet/vercel-action@v20
      with:
        vercel-args: ${{ ((github.event_name == 'push' && github.ref == 'refs/heads/master') && '--prod') || '' }}
        vercel-token: ${{ secrets.VERCEL_TOKEN }}
        vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
        vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
        scope: ${{ secrets.VERCEL_SCOPE }}
        github-token: ${{ secrets.GITHUB_TOKEN }}
